language: node_js
node_js:
- '0.10'
- '0.12'
deploy:
  provider: heroku
  api_key:
    secure: 3ygmLdlUsYskePtdfiOCNJvwAojAxHw/ePHRpSYHWBHL3yUZ0FmRmO/QSFvG5iujKQM9hkltIvV2FPE8pzkM4bonLFKsZovOKDa6Wqfn+IJwmnvzUOQSRuwwrJ2ZfAoreR4lfqTF7WSnBrP1chHxDekcXIUD3UR1c2LEhE9NRVOmTuMam2O28vVQFZP+w9x6Y3/Gjd0AqPuwLgaP4aeadQsnLHLDj22NWawH9Z68PFfmgfLPnuPgVRRZ2gIn8c/Q7DcpH+oXnxsiMZ21oaF+7pKMjyI7pp9MvKtVY8DXm/kjJ+lH7SkSRsW7/NrhPrD7L6J+luZBvdI7Zq5VILWlITE1kReVHnJH7IA64kyNm1K+0LSSnueHAj6Q3pg3UFbh1ZFbd5KxsQ7JG6tv/hRK0Xzdn/oRdP7C+wFImjTvwInxvomy7piaaVeFpPGVE+3wcp5GlCYLeHDGtxDrOfYFIyJz0/ZfrUomhHjQcbMTfxgIxaMbZaurOCdSG/lUzztlBJm0I4zJeFwLaUYp2cwlrCXW/kHoqgNv2GUkNmGu6odHzFcIYt1nXZGiU+Se8HCT35FuJbBtj487fig2F8k3mHF3bDoJtUuLOxTq43fMEB8Oq4JUYoALmTPjtRoVHVfpvYPhPK7TpXO7EJx/uv8AXQuTQt2k38rKsdgJEERNb6w=
  app: board-share
  on:
    repo: Boardshare/Boardshare
    branch: deploy